__This notebook is about implementing machine-learning algorithms, with the neural
networks, SVM, and cross-conformal prediction algorithms as examples. It is just for having
an understanding of ways to apply the ideas and algorithms of machine learning
in industry.__

__I am testing it on two dataset Wine dataset and USPS dataset__

__Wine Dataset__

__Task 1: Loading the wine dataset(Available in scikit learn)__

In [1]:
from sklearn.datasets import load_wine
Data_wine = load_wine()
print(Data_wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [2]:
print(Data_wine.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])


In [3]:
print(Data_wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [4]:
print((Data_wine.target))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [5]:
print(Data_wine.data.shape)

(178, 13)


__Task 2: Splitting the dataset into training and test set. Here in train_test_split() because I am not specifiying any split size so it's automatically be 3:1 for training and testing data__

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Data_wine['data'],Data_wine['target'],random_state=311)

In [7]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(133, 13)
(133,)
(45, 13)
(45,)


__Task 3: Using cross-validation and the training set only, estimating the generalization accuracy of the MLPClassifier with the default values of the parameters. I am using the function cross_val_score.__

In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
mlp1 = MLPClassifier(solver='adam', activation='relu', random_state=311, hidden_layer_sizes=[100],max_iter=200,alpha=0.0001).fit(X_train,y_train)
print(cross_val_score(mlp1, X_train, y_train, scoring='accuracy', cv=10))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multi

[0.71428571 0.78571429 0.78571429 0.69230769 0.92307692 0.92307692
 0.92307692 0.76923077 0.84615385 0.92307692]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


__Task 4: Trying to get rid of the warnings by varying a parameter, or parameters, such as
max_iter.Also  Estimating the generalization accuracy of the MLPClassifier
with the modified values of the parameters. (If there are no warnings, the
modified values of the parameters may be identical to the default values.)__

__Here I am changing the value of the solver optimisation algorithm from 'adam' to 'lbfgs' and activation function from 'relu' to 'tanh' in order
to avoid warnings. But we can also observe that our accuracy score has reduced drastically in order to avoid warnings.__

In [9]:
mlp2 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.0001).fit(X_train,y_train)
print(cross_val_score(mlp2, X_train, y_train, scoring='accuracy', cv=10))

[0.35714286 0.35714286 0.35714286 0.38461538 0.38461538 0.38461538
 0.46153846 0.46153846 0.38461538 0.38461538]


__Task 5: calculating the test error rate of the MLPClassifier with the modified values
of parameters, comparing it with the estimate obtained in the previous task
(task 4) for the same values of parameters, and write the observations in
a markdown cell of Jupyter notebook.__

In [10]:
predictions2 = mlp2.predict(X_test)
print(predictions2)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]


In [11]:
from sklearn.metrics import accuracy_score
A=accuracy_score(y_test,predictions2)
Test_error2 = 1-A
print('Test error for changed parameters of MLPClassifier:',round(Test_error2,2))

Test error for changed parameters of MLPClassifier: 0.58


In [12]:
predictions1 = mlp1.predict(X_test)
print(predictions1)

[1 1 1 1 1 0 0 2 0 1 1 0 0 2 1 1 2 0 2 1 1 1 2 0 2 1 1 2 2 1 2 0 0 1 1 1 0
 1 1 2 0 0 0 0 0]


In [13]:
B=accuracy_score(y_test,predictions1)
Test_error1 = 1-B
print('Test error for default parameters of MLPClassifier:',round(Test_error1,2))

Test error for default parameters of MLPClassifier: 0.13


__we can see, As expected the test error rate of MLPClassifier where we have changed the default parameters value is significantly high. It's highly overfitting on Training data and can't predict properly for testing data. All the predicted 
values belongs to First class only.
But the MLPClassifier with default parameters value has done considerable good and it's test error rate is acceptable in this case.__

__Task 6: Creating a pipeline for MLPClassifier involving data normalization and
MLPClassifier, and using grid search and cross-validation to tune parameter alpha for the pipeline, avoiding data snooping and data leakage.Additionally Experimenting with different ways of doing normalization (such as StandardScaler, MinMaxScaler,
RobustScaler, and Normalizer).__

In [14]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [15]:
pipe1 = Pipeline([("scaler",MinMaxScaler()),("mlp",MLPClassifier())])
pipe1.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('scaler', MinMaxScaler()), ('mlp', MLPClassifier())])

In [16]:
from sklearn.model_selection import GridSearchCV
param_grid = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
grid = GridSearchCV(pipe1, param_grid= param_grid)
grid.fit(X_train, y_train)
print(grid.best_params_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multi

{'mlp__alpha': 0.0001}


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [17]:
pipe2 = Pipeline([("scaler",RobustScaler()),("mlp",MLPClassifier())])
pipe2.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('scaler', RobustScaler()), ('mlp', MLPClassifier())])

__Task 7: Fiting the GridSearchCV object of task 6 to the training set and using it to
predict the test labels.__

In [18]:
param_grid2 = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
grid2 = GridSearchCV(pipe2, param_grid= param_grid2)
grid2.fit(X_train, y_train)
print(grid2.best_params_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multi

{'mlp__alpha': 0.001}


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [19]:
pipe3 = Pipeline([("scaler",Normalizer()),("mlp",MLPClassifier())])
pipe3.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('scaler', Normalizer()), ('mlp', MLPClassifier())])

In [20]:
param_grid3 = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
grid3 = GridSearchCV(pipe3, param_grid= param_grid3)
grid3.fit(X_train, y_train)
print(grid3.best_params_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multi

{'mlp__alpha': 0.1}


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [21]:
pipe4 = Pipeline([("scaler",StandardScaler()),("mlp",MLPClassifier())])
pipe4.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('scaler', StandardScaler()), ('mlp', MLPClassifier())])

In [22]:
param_grid4 = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
grid4 = GridSearchCV(pipe4, param_grid= param_grid4)
grid4.fit(X_train, y_train)
print(grid4.best_params_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multi

{'mlp__alpha': 0.1}


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


__As we can see, after applying different Normalization techniques we are getting different optimal values of alpha.__

__According to MinMaxScaler(), alpha = 0.01__

__According to RobustScaler(), alpha = 0.1__


__According to Normalizer(), alpha = 0.001__

__and According to StanderScaler(), alpha = 0.1__

__Now I am using these values of alpha to predict labels of test set.__ 

In [23]:
mlp3 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.01).fit(X_train,y_train)
print(cross_val_score(mlp3, X_train, y_train, scoring='accuracy', cv=10))

[0.35714286 0.35714286 0.35714286 0.38461538 0.38461538 0.38461538
 0.46153846 0.46153846 0.38461538 0.38461538]


In [24]:
predictions3 = mlp3.predict(X_test)
print(predictions3)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]


In [25]:
from sklearn.metrics import accuracy_score
c=accuracy_score(y_test,predictions3)
Test_error3 = 1-c
print('Test error for alpha=0.01 with MinMaxScaler:',round(Test_error3,2))

Test error for alpha=0.01 with MinMaxScaler: 0.58


In [26]:
mlp4 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.1).fit(X_train,y_train)
print(cross_val_score(mlp4, X_train, y_train, scoring='accuracy', cv=10))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITE

[0.57142857 0.71428571 0.57142857 0.84615385 0.61538462 1.
 0.92307692 0.92307692 0.92307692 0.92307692]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [27]:
predictions4 = mlp4.predict(X_test)
print(predictions4)

[1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0
 1 1 0 0 0 0 0 0]


In [28]:
d=accuracy_score(y_test,predictions4)
Test_error4 = 1-d
print('Test error for alpha=0.1 with RobustScaler:',round(Test_error4,2))

Test error for alpha=0.1 with RobustScaler: 0.29


In [29]:
mlp5 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.001).fit(X_train,y_train)
print(cross_val_score(mlp5, X_train, y_train, scoring='accuracy', cv=10))

[0.35714286 0.35714286 0.35714286 0.38461538 0.38461538 0.38461538
 0.46153846 0.46153846 0.38461538 0.38461538]


In [30]:
predictions5 = mlp5.predict(X_test)
print(predictions5)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]


In [31]:
e=accuracy_score(y_test,predictions5)
Test_error5 = 1-e
print('Test error for alpha=0.001 with Normalizer:',round(Test_error5,2))

Test error for alpha=0.001 with Normalizer: 0.58


__We can clearly see the Test error of every Normalization technique.
It's the same for MinMaxScaler, Normalizer and standardScaler. It's 58% which is really bad and a sign of overfiiting.
In all four techniques, RobustScaler perform quite well in comparison only which is 29% for error rate. Otherwise error rate of 
RobustScaler is also very high__

__I got curious and after playing around with different values of parameters, I came to conclusion that it really depends on data
and different parameters values. We can get really good results with lots of warnings which can be ignored, but atleast test
error rate will be good__

__For example__

In [32]:
mlp6 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[50],max_iter=100, alpha=0.001).fit(X_train,y_train)
print(cross_val_score(mlp6, X_train, y_train, scoring='accuracy', cv=10))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITE

[0.5        0.92857143 0.5        0.61538462 0.92307692 0.84615385
 0.69230769 1.         0.84615385 0.76923077]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [33]:
predictions6 = mlp6.predict(X_test)
print(predictions6)

[2 1 2 1 1 2 0 2 0 1 1 0 0 1 2 1 2 0 2 1 1 1 2 0 2 1 1 2 2 2 2 0 0 2 1 1 0
 1 1 2 0 0 0 0 0]


In [34]:
f=accuracy_score(y_test,predictions6)
Test_error6 = 1-f
print('Test error:',round(Test_error6,2))

Test error: 0.11


__So which Normalization technique to use depends on how and in which sense our data is dirty.__

__Task 8:Experimenting with a Support Vector Machine. Performing tasks 4–7 for the class
SVC in scikit-learn. Also trying The
parameters to fit using grid search are C and gamma.__

In [35]:
from sklearn.svm import SVC
pipe5 = Pipeline([("scaler",MinMaxScaler()),("svm",SVC())])
pipe5.fit(X_train,y_train)

Pipeline(steps=[('scaler', MinMaxScaler()), ('svm', SVC())])

In [36]:
param_grid5 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
grid5 = GridSearchCV(pipe5, param_grid=param_grid5)
grid5.fit(X_train, y_train)
print(grid5.best_params_)

{'svm__C': 1, 'svm__gamma': 1}


In [37]:
pipe6 = Pipeline([("scaler",RobustScaler()),("svm",SVC())])
pipe6.fit(X_train,y_train)

Pipeline(steps=[('scaler', RobustScaler()), ('svm', SVC())])

In [38]:
param_grid6 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
grid6 = GridSearchCV(pipe6, param_grid=param_grid6)
grid6.fit(X_train, y_train)
print(grid6.best_params_)

{'svm__C': 1, 'svm__gamma': 0.01}


In [39]:
pipe7 = Pipeline([("scaler",StandardScaler()),("svm",SVC())])
pipe7.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('svm', SVC())])

In [40]:
param_grid7 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
grid7 = GridSearchCV(pipe7, param_grid=param_grid7)
grid7.fit(X_train, y_train)
print(grid7.best_params_)

{'svm__C': 1, 'svm__gamma': 0.01}


In [41]:
pipe8 = Pipeline([("scaler",Normalizer()),("svm",SVC())])
pipe8.fit(X_train,y_train)

Pipeline(steps=[('scaler', Normalizer()), ('svm', SVC())])

In [42]:
param_grid8 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
grid8 = GridSearchCV(pipe8, param_grid=param_grid8)
grid8.fit(X_train, y_train)
print(grid8.best_params_)

{'svm__C': 100, 'svm__gamma': 100}


In [43]:
svc1 = SVC(C=1,gamma=0.01).fit(X_train,y_train)
print(cross_val_score(svc1, X_train, y_train, scoring='accuracy', cv=10))

[0.5        0.64285714 0.5        0.69230769 0.61538462 0.53846154
 0.61538462 0.61538462 0.69230769 0.84615385]


In [44]:
predictions7 = svc1.predict(X_test)
print(predictions7)

[1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 2 1 2 1 1 1 1 1 0
 1 1 1 0 0 0 0 1]


In [45]:
g=accuracy_score(y_test,predictions7)
Test_error7 = 1-g
print('Test error:',round(Test_error7,2))

Test error: 0.38


In [97]:
svc2 = SVC(C=1,gamma=1).fit(X_train,y_train)
print(cross_val_score(svc2, X_train, y_train, scoring='accuracy', cv=10))
predictions8 = svc2.predict(X_test)
print(predictions8)
h=accuracy_score(y_test,predictions8)
Test_error8 = 1-h
print('Test error:',round(Test_error8,2))

[0.35714286 0.35714286 0.35714286 0.38461538 0.38461538 0.38461538
 0.46153846 0.46153846 0.38461538 0.38461538]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]
Test error: 0.58


In [46]:
svc3 = SVC(C=100,gamma=100).fit(X_train,y_train)
print(cross_val_score(svc3, X_train, y_train, scoring='accuracy', cv=10))
predictions9 = svc3.predict(X_test)
print(predictions9)
i=accuracy_score(y_test,predictions9)
Test_error9 = 1-i
print('Test error:',round(Test_error9,2))

[0.35714286 0.35714286 0.35714286 0.38461538 0.38461538 0.38461538
 0.46153846 0.46153846 0.38461538 0.38461538]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]
Test error: 0.58


__we can see, it is somewhat similar to our previous case when we were having MLPClassifier instead of support vector classifier and like previously if we play around different values and expand our choices, we can get good result(Good Enough to work).__

In [47]:
svc4 = SVC(C=11,gamma=0.001).fit(X_train,y_train)
print(cross_val_score(svc4, X_train, y_train, scoring='accuracy', cv=10))
predictions10 = svc4.predict(X_test)
print(predictions10)
j=accuracy_score(y_test,predictions10)
Test_error10 = 1-j
print('Test error:',round(Test_error10,2))

[0.64285714 0.71428571 0.57142857 0.53846154 0.84615385 0.84615385
 0.69230769 0.84615385 0.84615385 0.92307692]
[1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 2 1 1 2 0 2 1 1 2 2 2 2 0 0 1 1 1 0
 0 1 2 0 0 0 0 0]
Test error: 0.16


# USPS Dataset

__Normalized handwritten digits, automatically
scanned from envelopes by the U.S. Postal Service. The original
scanned digits are binary and of different sizes and orientations; the
images  here have been deslanted and size normalized, resulting
in 16 x 16 grayscale images (Le Cun et al., 1990).__


__There are 7291 training observations and 2007 test observations,
distributed as follows:
         0    1   2   3   4   5   6   7   8   9 Total
Train 1194 1005 731 658 652 556 664 645 542 644 7291
 Test  359  264 198 166 200 160 170 147 166 177 2007__

__or as proportions:
         0    1   2    3    4    5    6    7    8    9 
Train 0.16 0.14 0.1 0.09 0.09 0.08 0.09 0.09 0.07 0.09
 Test 0.18 0.13 0.1 0.08 0.10 0.08 0.08 0.07 0.08 0.09.__

__Task 1__

In [50]:
import numpy as np
import pandas as pd
USPS = np.genfromtxt('USPSTrain.txt')

In [51]:
USPS.shape

(7291, 257)

In [52]:
df = pd.DataFrame(USPS)

In [53]:
print(df.head())

   0    1    2    3      4      5      6      7      8      9    ...    247  \
0  6.0 -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -0.631  0.862  ...  0.304   
1  5.0 -1.0 -1.0 -1.0 -0.813 -0.671 -0.809 -0.887 -0.671 -0.853  ... -0.671   
2  4.0 -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000  ... -1.000   
3  7.0 -1.0 -1.0 -1.0 -1.000 -1.000 -0.273  0.684  0.960  0.450  ... -0.318   
4  3.0 -1.0 -1.0 -1.0 -1.000 -1.000 -0.928 -0.204  0.751  0.466  ...  0.466   

     248    249    250    251    252    253    254    255  256  
0  0.823  1.000  0.482 -0.474 -0.991 -1.000 -1.000 -1.000 -1.0  
1 -0.671 -0.033  0.761  0.762  0.126 -0.095 -0.671 -0.828 -1.0  
2 -1.000 -1.000 -0.109  1.000 -0.179 -1.000 -1.000 -1.000 -1.0  
3  1.000  0.536 -0.987 -1.000 -1.000 -1.000 -1.000 -1.000 -1.0  
4  0.639  1.000  1.000  0.791  0.439 -0.199 -0.883 -1.000 -1.0  

[5 rows x 257 columns]


In [54]:
y=df.iloc[:,0]
print('Labels:\n',y)

Labels:
 0       6.0
1       5.0
2       4.0
3       7.0
4       3.0
       ... 
7286    3.0
7287    3.0
7288    3.0
7289    0.0
7290    1.0
Name: 0, Length: 7291, dtype: float64


In [55]:
x = df.iloc[:,1:]
print('Features:\n',x)

Features:
       1    2    3      4      5      6      7      8      9      10   ...  \
0    -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -0.631  0.862 -0.167  ...   
1    -1.0 -1.0 -1.0 -0.813 -0.671 -0.809 -0.887 -0.671 -0.853 -1.000  ...   
2    -1.0 -1.0 -1.0 -1.000 -1.000 -1.000 -1.000 -1.000 -1.000 -0.996  ...   
3    -1.0 -1.0 -1.0 -1.000 -1.000 -0.273  0.684  0.960  0.450 -0.067  ...   
4    -1.0 -1.0 -1.0 -1.000 -1.000 -0.928 -0.204  0.751  0.466  0.234  ...   
...   ...  ...  ...    ...    ...    ...    ...    ...    ...    ...  ...   
7286 -1.0 -1.0 -1.0 -0.988 -0.527 -0.208  0.620  1.000  0.467  0.396  ...   
7287 -1.0 -1.0 -1.0 -0.990  0.708  0.557  0.347 -0.107 -0.758 -0.975  ...   
7288 -1.0 -1.0 -1.0 -0.783 -0.984 -0.827  0.068  1.000  1.000  1.000  ...   
7289 -1.0 -1.0 -1.0 -1.000 -1.000 -0.549  0.463  0.999  0.999  0.999  ...   
7290 -1.0 -1.0 -1.0 -1.000 -1.000 -0.108  1.000  0.616 -0.867 -1.000  ...   

        247    248    249    250    251    252    253    254    

__Task 2__

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, Y_train, Y_test = train_test_split(x,y,random_state=311)

In [57]:
print(x_train.shape)
print(Y_train.shape)
print(x_test.shape)
print(Y_test.shape)

(5468, 256)
(5468,)
(1823, 256)
(1823,)


__Task 3__

In [58]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
MLP1 = MLPClassifier(solver='adam', activation='relu', random_state=311, hidden_layer_sizes=[100],max_iter=200,alpha=0.0001).fit(x_train,Y_train)
print(cross_val_score(MLP1, x_train, Y_train, scoring='accuracy', cv=10))

[0.96709324 0.95978062 0.96892139 0.9725777  0.976234   0.96160878
 0.96343693 0.95429616 0.96520147 0.97802198]


__Task 4__

In [59]:
MLP2 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.0001).fit(x_train,Y_train)
print(cross_val_score(MLP2, x_train, Y_train, scoring='accuracy', cv=10))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITE

[0.91224863 0.91590494 0.9213894  0.89945155 0.91224863 0.93235832
 0.90859232 0.90127971 0.91025641 0.92307692]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [60]:
Predictions2 = MLP2.predict(x_test)
print(Predictions2)

[1. 4. 2. ... 6. 3. 3.]


In [61]:
from sklearn.metrics import accuracy_score
a=accuracy_score(Y_test,Predictions2)
error2 = 1-a
print('Test error for changed parameters of MLPClassifier:',round(error2,2))

Test error for changed parameters of MLPClassifier: 0.08


In [62]:
Predictions1 = MLP1.predict(x_test)
print(Predictions1)

[1. 4. 2. ... 6. 3. 3.]


In [63]:
b=accuracy_score(Y_test,Predictions1)
error1 = 1-b
print('Test error for default parameters of MLPClassifier:',round(error1,2))

Test error for default parameters of MLPClassifier: 0.03


__Task 6 and 7__

In [64]:
PIPE1 = Pipeline([("scaler",MinMaxScaler()),("mlp",MLPClassifier())])
pipe1.fit(x_train, Y_train)

Pipeline(steps=[('scaler', MinMaxScaler()), ('mlp', MLPClassifier())])

In [65]:
from sklearn.model_selection import GridSearchCV
param_grid = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
GRID1 = GridSearchCV(PIPE1, param_grid= param_grid)
GRID1.fit(x_train, Y_train)
print(GRID1.best_params_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


{'mlp__alpha': 0.1}


In [66]:
PIPE2 = Pipeline([("scaler",RobustScaler()),("mlp",MLPClassifier())])
PIPE2.fit(x_train, Y_train)

Pipeline(steps=[('scaler', RobustScaler()), ('mlp', MLPClassifier())])

In [67]:
param_grid2 = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
GRID2 = GridSearchCV(PIPE2, param_grid= param_grid2)
GRID2.fit(x_train, Y_train)
print(GRID2.best_params_)

{'mlp__alpha': 0.0001}


In [68]:
PIPE3 = Pipeline([("scaler",Normalizer()),("mlp",MLPClassifier())])
PIPE3.fit(x_train, Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Pipeline(steps=[('scaler', Normalizer()), ('mlp', MLPClassifier())])

In [69]:
param_grid3 = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
GRID3 = GridSearchCV(PIPE3, param_grid= param_grid3)
GRID3.fit(x_train, Y_train)
print(GRID3.best_params_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multi

{'mlp__alpha': 0.01}


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [70]:
PIPE4 = Pipeline([("scaler",StandardScaler()),("mlp",MLPClassifier())])
PIPE4.fit(x_train, Y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('mlp', MLPClassifier())])

In [71]:
param_grid4 = {'mlp__alpha':[0.1,0.01,.001,0.0001,0.00001,1]}
GRID4 = GridSearchCV(pipe4, param_grid= param_grid4)
GRID4.fit(x_train, Y_train)
print(GRID4.best_params_)

{'mlp__alpha': 1}


In [72]:
MLP3 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.01).fit(x_train,Y_train)
print(cross_val_score(MLP3, x_train, Y_train, scoring='accuracy', cv=10))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITE

[0.90310786 0.91224863 0.92870201 0.91407678 0.91773309 0.92870201
 0.91590494 0.90859232 0.90842491 0.91941392]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [73]:
Predictions3 = MLP3.predict(x_test)
print(Predictions3)

[1. 4. 2. ... 6. 3. 3.]


In [74]:
from sklearn.metrics import accuracy_score
cc=accuracy_score(Y_test,Predictions3)
error3 = 1-cc
print('Test error for alpha=0.01 with MinMaxScaler:',round(error3,2))

Test error for alpha=0.01 with MinMaxScaler: 0.08


In [75]:
MLP4 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.1).fit(x_train,Y_train)
print(cross_val_score(MLP4, x_train, Y_train, scoring='accuracy', cv=10))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITE

[0.9213894  0.91956124 0.91956124 0.91224863 0.9213894  0.93053016
 0.91773309 0.91407678 0.91208791 0.93223443]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [76]:
Predictions4 = MLP4.predict(x_test)
print(Predictions4)

[1. 4. 2. ... 6. 3. 3.]


In [77]:
dd=accuracy_score(Y_test,Predictions4)
error4 = 1-dd
print('Test error for alpha=0.1 with RobustScaler:',round(error4,2))

Test error for alpha=0.1 with RobustScaler: 0.08


In [78]:
MLP5 = MLPClassifier(solver='lbfgs', activation='tanh', random_state=311, hidden_layer_sizes=[10],max_iter=200, alpha=0.001).fit(x_train,Y_train)
print(cross_val_score(MLP5, x_train, Y_train, scoring='accuracy', cv=10))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITE

[0.91773309 0.90859232 0.92321755 0.90127971 0.91773309 0.93784278
 0.91042048 0.90859232 0.91025641 0.91758242]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [79]:
Predictions5 = MLP5.predict(x_test)
print(Predictions5)

[1. 4. 2. ... 6. 3. 3.]


In [80]:
ee=accuracy_score(Y_test,Predictions5)
error5 = 1-ee
print('Test error for alpha=0.001 with Normalizer:',round(error5,2))

Test error for alpha=0.001 with Normalizer: 0.08


__Task 8__

In [81]:
PIPE5 = Pipeline([("scaler",MinMaxScaler()),("svm",SVC())])
PIPE5.fit(x_train,Y_train)

Pipeline(steps=[('scaler', MinMaxScaler()), ('svm', SVC())])

In [82]:
param_grid5 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
GRID5 = GridSearchCV(PIPE5, param_grid=param_grid5)
GRID5.fit(x_train, Y_train)
print(GRID5.best_params_)

{'svm__C': 100, 'svm__gamma': 0.01}


In [83]:
PIPE6 = Pipeline([("scaler",RobustScaler()),("svm",SVC())])
PIPE6.fit(x_train,Y_train)

Pipeline(steps=[('scaler', RobustScaler()), ('svm', SVC())])

In [84]:
param_grid6 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
GRID6 = GridSearchCV(PIPE6, param_grid=param_grid6)
GRID6.fit(x_train, Y_train)
print(GRID6.best_params_)

{'svm__C': 100, 'svm__gamma': 0.01}


In [85]:
PIPE7 = Pipeline([("scaler",StandardScaler()),("svm",SVC())])
PIPE7.fit(x_train,Y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('svm', SVC())])

In [86]:
param_grid7 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
GRID7 = GridSearchCV(PIPE7, param_grid=param_grid7)
GRID7.fit(x_train, Y_train)
print(GRID7.best_params_)

{'svm__C': 10, 'svm__gamma': 0.01}


In [87]:
PIPE8 = Pipeline([("scaler",Normalizer()),("svm",SVC())])
PIPE8.fit(x_train,Y_train)

Pipeline(steps=[('scaler', Normalizer()), ('svm', SVC())])

In [88]:
param_grid8 = {'svm__C': [0.01,0.1,1,10,100],
             'svm__gamma': [0.01,0.1,1,10,100]}
GRID8 = GridSearchCV(PIPE8, param_grid=param_grid8)
GRID8.fit(x_train, Y_train)
print(GRID8.best_params_)

{'svm__C': 100, 'svm__gamma': 1}


In [89]:
SVC1 = SVC(C=1,gamma=0.01).fit(x_train,Y_train)
print(cross_val_score(SVC1, x_train, Y_train, scoring='accuracy', cv=10))

[0.98171846 0.976234   0.97440585 0.97806216 0.98354662 0.97440585
 0.97989031 0.97074954 0.97069597 0.98717949]


In [90]:
Predictions7 = SVC1.predict(x_test)
print(Predictions7)

[1. 4. 2. ... 6. 3. 3.]


In [91]:
gg=accuracy_score(Y_test,Predictions7)
error7 = 1-gg
print('Test error:',round(error7,2))

Test error: 0.02


In [92]:
SVC2 = SVC(C=1,gamma=1).fit(x_train,Y_train)
print(cross_val_score(SVC2, x_train, Y_train, scoring='accuracy', cv=10))
Predictions8 = SVC2.predict(x_test)
print(Predictions8)
hh=accuracy_score(Y_test,Predictions8)
error8 = 1-hh
print('Test error:',round(error8,2))

[0.21937843 0.21937843 0.21755027 0.2047532  0.21023766 0.24131627
 0.2285192  0.21389397 0.21611722 0.22161172]
[1. 0. 0. ... 0. 0. 0.]
Test error: 0.77


In [93]:
SVC3 = SVC(C=100,gamma=100).fit(x_train,Y_train)
print(cross_val_score(SVC3, x_train, Y_train, scoring='accuracy', cv=10))
Predictions9 = SVC3.predict(x_test)
print(Predictions9)
ii=accuracy_score(Y_test,Predictions9)
error9 = 1-ii
print('Test error:',round(error9,2))

[0.16453382 0.16453382 0.16270567 0.16270567 0.16270567 0.16453382
 0.16453382 0.16453382 0.16483516 0.16483516]
[0. 0. 0. ... 0. 0. 0.]
Test error: 0.84


In [94]:
SVC4 = SVC(C=11,gamma=0.001).fit(x_train,Y_train)
print(cross_val_score(SVC4, x_train, Y_train, scoring='accuracy', cv=10))
Predictions10 = SVC4.predict(x_test)
print(Predictions10)
jj=accuracy_score(Y_test,Predictions10)
error10 = 1-jj
print('Test error:',round(error10,2))

[0.97440585 0.96892139 0.95978062 0.97074954 0.97440585 0.96526508
 0.96526508 0.96343693 0.96886447 0.97435897]
[1. 4. 2. ... 6. 3. 3.]
Test error: 0.03


__EXTRA__

In [95]:
extra_predictions1 = mlp2.predict_proba(X_test)
print(extra_predictions1)

[[0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27067671]
 [0.33834581 0.39097748 0.27

In [96]:
extra_predictions2 = mlp1.predict_proba(X_test)
print(extra_predictions2)

[[5.47182082e-03 8.78703630e-01 1.15824550e-01]
 [2.95264794e-01 4.78661470e-01 2.26073736e-01]
 [9.01236759e-05 8.93518090e-01 1.06391786e-01]
 [7.99145906e-03 8.44483718e-01 1.47524823e-01]
 [1.94121112e-04 9.26930532e-01 7.28753471e-02]
 [6.25379457e-01 5.03903486e-02 3.24230194e-01]
 [9.99859063e-01 6.33191010e-06 1.34605225e-04]
 [1.08463130e-02 5.81015946e-02 9.31052092e-01]
 [9.99760921e-01 2.60288559e-06 2.36476246e-04]
 [1.49546407e-04 9.79242238e-01 2.06082161e-02]
 [1.04016619e-02 9.15488010e-01 7.41103284e-02]
 [8.05494817e-01 9.73805295e-02 9.71246531e-02]
 [9.99999692e-01 1.58564047e-10 3.07748124e-07]
 [1.21900030e-03 4.05703420e-01 5.93077580e-01]
 [1.98407962e-01 6.04236401e-01 1.97355636e-01]
 [7.30665070e-04 9.06053477e-01 9.32158584e-02]
 [4.61989909e-03 3.09493284e-02 9.64430772e-01]
 [9.72192663e-01 6.86004242e-03 2.09472951e-02]
 [2.46485651e-03 7.27172141e-02 9.24817929e-01]
 [1.98405825e-03 9.04481454e-01 9.35344874e-02]
 [6.27803285e-03 9.28858355e-01 6.486361

__When using the method predict_proba in MLPClassifier it might be
necessary to avoid applying it to one test sample; it may or may not give
wrong results. It is safe
to apply it to whole test set at once.
GridSearchCV runs only on one thread by default. If you set the variable
n_jobs = -1 in GridSearchCV then it allows the function to run on all
threads of your CPU (n_jobs = -2 runs on all but one thread etc.). It
may improve the run-time considerably__